import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans, Geist_Mono, Poppins, Dosis, Nunito } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({ 
  variable: "--font-inter", 
  subsets: ["latin"], 
  weight: ["300", "400", "500", "600", "700"],
  display: "swap"
});
const jakartaSans = Plus_Jakarta_Sans({ 
  variable: "--font-jakarta", 
  subsets: ["latin"], 
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap"
});
const poppins = Poppins({ 
  variable: "--font-poppins", 
  subsets: ["latin"], 
  weight: ["300", "400", "500", "600", "700"],
  display: "swap"
});
const dosis = Dosis({ 
  variable: "--font-dosis", 
  subsets: ["latin"], 
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  display: "swap"
});
const nunito = Nunito({ 
  variable: "--font-nunito", 
  subsets: ["latin"], 
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
  style: ["normal", "italic"],
  display: "swap"
});
const geistMono = Geist_Mono({ 
  variable: "--font-geist-mono", 
  subsets: ["latin"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Guide Me",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1, maximum-scale=1",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${jakartaSans.variable} ${poppins.variable} ${dosis.variable} ${nunito.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}